create table if not exists public.profiles (
    id bigint generated by default as identity unique not null,
    user_id uuid primary key references auth.users (id) on delete cascade,
    nomor_hp text not null unique,
    nama text not null,
    jenis_pengguna text not null check (jenis_pengguna in ('siswa', 'mahasiswa')),
    kelas text not null default '',
    bidang text not null default '',
    qr_code text not null unique,
    aktif boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "Users and admins can read profiles"
on public.profiles
for select
to authenticated
using (
    auth.uid() = user_id
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
);

grant select on public.profiles to authenticated;